### ISSUE TITLE
Transparency not working (ubuntu)

### ISSUE THREAD

**Issue by drasill** [nickforddesign/vuebersicht#3]
Hi,

it seems I've been hit by https://github.com/electron/electron/issues/2170.

Adding a delay before creating the window did the trick (I tried with 200ms as minimum).

`background.ts:42` : 
```js
app.on('ready', async () => {
  await new Promise(resolve => setTimeout(resolve, 200)) // delay
  if (isDevelopment && !process.env.IS_TEST) {
```

As it is kind of specific, I can't really make a PR, but other may encounter this.

**Comment by nickforddesign** [comment]
I've added this in 67c0868, I haven't personally tested it so if you could pull the latest and confirm I'd appreciate it!
